### ISSUE TITLE
If private file area is deleted (e.g. via FTP), uploading new file leads to unexplained behaviour.

### ISSUE THREAD

**Issue by ssteinerx** [marvinlabs/customer-area#102]
This issue occurs when the customer-area private folder for the owner is deleted behind the scenes.  While this should never occur in practice, the error handling is less than ideal...it deletes the post (while leaving the file in place) and 404s.

It should probably either recreate the directory or, at least, tell the user why the upload failed.

**Comment by vpratfr** [comment]
This should be fixed with the new upload system. Re-open if you still experience it.
