### ISSUE TITLE
"Empty Trash" in private files only removes those items visible on the current page

### ISSUE THREAD

**Issue by ssteinerx** [marvinlabs/customer-area#104]
Only the visible items are removed instead of removing all items in the trash.

**Comment by ssteinerx** [comment]
Only if you have duplicate posts for the same file (programmer error).

**Comment by ssteinerx** [comment]
Even after fixing my bug, this is still true.

**Comment by ssteinerx** [comment]
It also always goes back to viewing all files, so selectively removing things from the trash is extremely cumbersome when dealing with large groups of files.

**Comment by vpratfr** [comment]
Should be closed in develop. Please confirm and close the issue if that is the case.
