### ISSUE TITLE
Using wpca-twenty-twelve theme, sidebar widget display on "Dashboard" doesn't show Archives or Categories

### ISSUE THREAD

**Issue by ssteinerx** [marvinlabs/customer-area#105]
Going to Files->My Files correctly displays the Categories and Archives.

**Comment by vpratfr** [comment]
I could not reproduce this. Here is what I have for a subscriber for example:

![image](https://cloud.githubusercontent.com/assets/2526465/7456137/779cecf8-f282-11e4-8e21-60ae734ba6b6.png)


Make sure the user has content assigned. Else nothing is shown.
