### ISSUE TITLE
Invalid argument to foreach in log view

### ISSUE THREAD

**Issue by ssteinerx** [marvinlabs/customer-area#107]
2015/04/27 - 11:25:02	Owner changed	File 944	IP admin	
Warning: Invalid argument supplied for foreach() in /home/xxx/public_html/wp-content/plugins/customer-area/src/php/core-addons/log/log-table.class.php on line 203

There is one of these in the "Extra info" column for every entry.

**Comment by vpratfr** [comment]
Hi,

Do you still see this issue on the develop branch?

**Comment by ssteinerx** [comment]
I'll switch back to develop now that you've merged and let youknow.

**Comment by ssteinerx** [comment]
https://www.dropbox.com/s/54l2nxe93vrrwbf/Screenshot%202015-05-01%2013.57.02.png?dl=0
After installing newest extra modules, pulling latest development branch, deactivating and reactivating main plugin.

**Comment by vpratfr** [comment]
Is this file created automatically? Do you know its owner? Is that a valid
owner?

**Comment by ssteinerx** [comment]
I created that file by direct upload and it's owned by a managed group that I picked from the dropdown and the group definitely exists.

**Comment by vpratfr** [comment]
Thanks. Fixed in develop.
