### ISSUE TITLE
WP Customer Area menu at top shows menu choices user is not authorized to perform.

### ISSUE THREAD

**Issue by ssteinerx** [marvinlabs/customer-area#108]
This is not good for two reasons:
  
  1> If they're not authorized to access the area, we probably don't really want them to know more about how the plugin(s) are organized.  They don't need to know.

  2> They get a plain error window when they choose the function:
        You do not have sufficient permissions to access this page.

The menu should be filtered based on the functions the user is actually authorized to perform.

**Comment by vpratfr** [comment]
I think this is because you need some addon updates. I'll send them over by
email soon.

**Comment by ssteinerx** [comment]
Great, thank you!

Steve

**Comment by vpratfr** [comment]
You've got mail. Let me know if that solves the problem.

**Comment by ssteinerx** [comment]
https://www.dropbox.com/s/54l2nxe93vrrwbf/Screenshot%202015-05-01%2013.57.02.png?dl=0

**Comment by ssteinerx** [comment]
This is after deactivating and reactivating a checkout of fully updated customer-area 6.1.0 development branch.

**Comment by ssteinerx** [comment]
Identical problem.  This is a lowly subscriber and can still see all admin options in the menu:

https://www.dropbox.com/s/76s9i33f4fajufk/Screenshot%202015-05-01%2014.24.34.png?dl=0

**Comment by vpratfr** [comment]
Thanks, fixed in develop.

**Comment by ssteinerx** [comment]
Thanks!  Will confirm later today.
