### ISSUE TITLE
Customer-area main plugin self-identifies as 6.1.0, shortcodes plugin seems to be triggering warning

### ISSUE THREAD

**Issue by ssteinerx** [marvinlabs/customer-area#109]
The only plugin (on develop branch) that claims it needs 6.1.0 is shortcodes.

Customer-area main plugin says it's 6.1.0, but I still get this warning:

Outdated plugin version

Some add-ons require a newer version of the main plugin (you are currently running version 6.1.0). You can find the list of all add-ons on the add-ons status pages.

**Comment by vpratfr** [comment]
Deactivate and  reactivate

**Comment by ssteinerx** [comment]
Deactivate and reactivate what?

**Comment by vpratfr** [comment]
The main plugin
