### ISSUE TITLE
Shortcode for user groups

### ISSUE THREAD

**Issue by vpratfr** [marvinlabs/customer-area#115]
From: http://wp-customerarea.com/support/topic/automatically-add-users-to-user-groups-based-on-field-in-registration-form/

Would be good to have a shortcode to display the groups of a user.

Could be nice to have that shown on the profile page (with a setting to enable/disable)

**Comment by OrigamiPenguin** [comment]
Hi there. I originally set up this request on the WP-Customer Area Forum. Have you got any news on adding this to an update?

My configuration requires the Users to be separated into "Companies". Documents can then be accessed by everyone within the company. I have used the User Groups add on to create the "Companies", but my client requires the Private area to show a company logo and description once they are logged in.

If a Meta Field called "Group Description" was added to the "User Groups" along with the option to add a "Featured Image", could we then have a shortcode or widget to output the data on the front end?

**Comment by vpratfr** [comment]
Hi,

I'm working on the next release currently and what you require is pretty specific. This could be done quite easily with some custom development:

- Use ACF or any other custom field plugin to attach extra information to the post type `cuar_user_group`

Then in your template:

- Get all user groups of a user (see snippet below)
- Get the meta for that group and print it

```
$ug_addon = cuar_addon('user-group')
$user_groups = $ug_addon->get_groups_of_user($user_id); // Array of WP_Post objects
```

So I'll be closing this feature request for now. Do not hesitate to post a support request on the forum if you can't get it to work.
