### ISSUE TITLE
Error Message after updating main plugin

### ISSUE THREAD

**Issue by lennynld** [marvinlabs/customer-area#119]
WP Customer Area has identified a number of potential problems:

     Some Client Zone extensions need a newer version of the basic plugin.

**Comment by vpratfr** [comment]
Deactivate and then reactivate the main plugin. This should go away.

**Comment by lennynld** [comment]
After the main plugin was updated it stayed in the 6.0.0 version,
after reactivating the plugin it changed to 6.1.1

but its fixed.
