### ISSUE TITLE
"Pages" shows up in customer area even with pages addon disabled in 

### ISSUE THREAD

**Issue by ssteinerx** [marvinlabs/customer-area#126]
In "Private Pages" tab, when this is unchecked, I'd expect the "Pages" menu to disappear from the dashboard.

Enable add-on	 [ ] Check this to enable the private pages add-on.

It's there regardless of the state of this checkbox.

**Comment by ssteinerx** [comment]
It does not show up in the admin dashboard in the left hand menu, but does show on the customer's dashboard.

**Comment by vpratfr** [comment]
Fixed. Will be in next release.
