### ISSUE TITLE
Notifications mails headers and role issues

### ISSUE THREAD

**Issue by tlartaud** [marvinlabs/customer-area#131]
## What is this about ?
> Issue related to this [support thread](http://wp-customerarea.com/support/topic/notifications-not-working/)

### I've created two accounts :
- admin : admin@mydomain.com
- user : user@gmail.com

### Tests results :
- Conversation from admin to admin -> notification received
- Conversation from admin to user -> notification not received (no php error message)
- Conversation from admin to subscriber role -> notification not received (but have php error message)
- Conversation from admin to administrator role -> notification not received (but have php error message)
- Conversation from user to admin -> notification received
- Conversation from user to user -> notification not received (no php error message)

> At this state, we can really suspect one issue precisely, let's verify that.

### Created a new account :
- user2 : user@mydomain.com

### Some tests with user2 :
- Conversation from admin to user2 -> notification received
- Conversation from admin to subscriber role -> notification not received (but have php error message)
- Conversation from user2 to user -> notification not received (no php error message)
- Conversation from user to user2 -> notification received

> At this point, my doubts are confirmed by the tests. Gmail simply block notification mails from WPCA.
> To be sure that this is a general issue, and not an issue related to the conversation add-on, i've tried to click a file download link while connected as user, and i did not received any mail, but i can receive them while connected as user2.

## Analysis
To conclude, there's 2 issues.

### First issue : Gmail
First one is a general issue about Gmail blocking mails from your server ( see errors below ), or Gmail unaccessible (i've performed some tests from a local vagrant wp installation, my postfix is not properly configured, more tests about gmail should be done on a production environment with properly configured sendmail or postfix program.)
```
$vagrant@vvv:/var/log$ sudo nano mail.log

Jun  8 15:35:36 vvv postfix/smtp[3714]: D6ACB6127D: to=<admin@mydomain.com>, relay=mydomain.com[37.187.181.155]:25, delay=0.28, delays=0/0/0.11/0.17, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as CEDDC9F675)
Jun  8 15:35:36 vvv postfix/qmgr[1346]: D6ACB6127D: removed
Jun  8 15:35:36 vvv postfix/smtp[3637]: E5A3A6127E: to=<admin@mydomain.com>, relay=mydomain.com[37.187.181.155]:25, delay=0.29, delays=0/0/0.11/0.17, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as E0F14A0A38)
Jun  8 15:35:36 vvv postfix/qmgr[1346]: E5A3A6127E: removed
Jun  8 15:36:34 vvv postfix/sendmail[3769]: warning: /etc/postfix/main.cf, line 41: overriding earlier entry: inet_protocols=all
Jun  8 15:36:34 vvv postfix/postdrop[3770]: warning: /etc/postfix/main.cf, line 41: overriding earlier entry: inet_protocols=all
Jun  8 15:36:34 vvv postfix/pickup[1345]: 029156127D: uid=33 from=<www-data>
Jun  8 15:36:34 vvv postfix/cleanup[3687]: 029156127D: message-id=<3882db16db8a2568127867aad97372d3@local.wordpress.dev>
Jun  8 15:36:34 vvv postfix/qmgr[1346]: 029156127D: from=<www-data@vvv>, size=1052, nrcpt=1 (queue active)
Jun  8 15:36:34 vvv postfix/smtp[3696]: 029156127D: to=<user@mydomain.com>, relay=mydomain.com[37.187.181.155]:25, delay=0.24, delays=0/0/0.1/0.14, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as EF6469F675)
Jun  8 15:36:34 vvv postfix/qmgr[1346]: 029156127D: removed
Jun  8 15:39:22 vvv postfix/qmgr[1346]: EC63361262: from=<www-data@vvv>, size=1042, nrcpt=1 (queue active)
Jun  8 15:39:22 vvv postfix/trivial-rewrite[3867]: warning: /etc/postfix/main.cf, line 41: overriding earlier entry: inet_protocols=all
Jun  8 15:39:22 vvv postfix/qmgr[1346]: AFF7361279: from=<www-data@vvv>, size=1044, nrcpt=1 (queue active)
Jun  8 15:39:22 vvv postfix/qmgr[1346]: 4840F61275: from=<www-data@vvv>, size=1041, nrcpt=1 (queue active)
Jun  8 15:39:22 vvv postfix/qmgr[1346]: 68ABD6126C: from=<www-data@vvv>, size=1048, nrcpt=1 (queue active)
Jun  8 15:39:22 vvv postfix/smtp[3868]: warning: /etc/postfix/main.cf, line 41: overriding earlier entry: inet_protocols=all
Jun  8 15:39:22 vvv postfix/smtp[3869]: warning: /etc/postfix/main.cf, line 41: overriding earlier entry: inet_protocols=all
Jun  8 15:39:22 vvv postfix/smtp[3870]: warning: /etc/postfix/main.cf, line 41: overriding earlier entry: inet_protocols=all
Jun  8 15:39:22 vvv postfix/smtp[3871]: warning: /etc/postfix/main.cf, line 41: overriding earlier entry: inet_protocols=all
Jun  8 15:39:52 vvv postfix/smtp[3870]: connect to gmail.com[216.58.208.197]:25: Connection timed out
Jun  8 15:39:52 vvv postfix/smtp[3869]: connect to gmail.com[216.58.208.197]:25: Connection timed out
Jun  8 15:39:52 vvv postfix/smtp[3868]: connect to gmail.com[216.58.208.197]:25: Connection timed out
Jun  8 15:39:52 vvv postfix/smtp[3871]: connect to gmail.com[216.58.208.197]:25: Connection timed out
Jun  8 15:39:52 vvv postfix/bounce[3872]: warning: /etc/postfix/main.cf, line 41: overriding earlier entry: inet_protocols=all
Jun  8 15:39:52 vvv postfix/smtp[3870]: 4840F61275: to=<user@gmail.com>, relay=none, delay=1076, delays=1046/0.02/30/0, dsn=4.4.1, status=deferred (connect to gmail.com[216.58.208.197]:25: Connection timed out)
Jun  8 15:39:52 vvv postfix/smtp[3869]: AFF7361279: to=<user@gmail.com>, relay=none, delay=511, delays=481/0.02/30/0, dsn=4.4.1, status=deferred (connect to gmail.com[216.58.208.197]:25: Connection timed out)
Jun  8 15:39:52 vvv postfix/smtp[3868]: EC63361262: to=<user@gmail.com>, relay=none, delay=2342, delays=2312/0.02/30/0, dsn=4.4.1, status=deferred (connect to gmail.com[216.58.208.197]:25: Connection timed out)
Jun  8 15:39:52 vvv postfix/smtp[3871]: 68ABD6126C: to=<user@gmail.com>, relay=none, delay=1577, delays=1547/0.03/30/0, dsn=4.4.1, status=deferred (connect to gmail.com[216.58.208.197]:25: Connection timed out)
Jun  8 15:39:52 vvv postfix/bounce[3873]: warning: /etc/postfix/main.cf, line 41: overriding earlier entry: inet_protocols=all
```

I didn't checked the code, and how wp_mail is used, but i suspect a server misconfiguration. In the logs, we can read : "from=<www-data@vvv>". Google will not accept that. Google fight spammers, and does not accept to receive a mail from a sendmail program where the from field domain is different from the sender domain (that's why it must also be tested on a production environment, with a correctly configured postfix program, and not a one from vagrant)
 
### Second issue : PHP error when sending conversation to role

When I select an user role, and send a conversation, I have the following errors messages :
```
<b>Notice</b>:  Trying to get property of non-object in <b>/srv/wpca-plugins/customer-area-notifications/src/php/notifications-addon.class.php</b> on line <b>515</b><br>
<br>
<b>Notice</b>:  Trying to get property of non-object in <b>/srv/wpca-plugins/customer-area-notifications/src/php/notifications-addon.class.php</b> on line <b>515</b><br>
<br>
<b>Notice</b>:  Trying to get property of non-object in <b>/srv/wpca-plugins/customer-area-notifications/src/php/notifications-addon.class.php</b> on line <b>413</b><br>
<br>
<b>Notice</b>:  Trying to get property of non-object in <b>/srv/wpca-plugins/customer-area-notifications/src/php/notifications-addon.class.php</b> on line <b>414</b><br>
```

**Comment by vpratfr** [comment]
Fixed the second issue (was a bug in Additional owner types). For 1st issue, I can't do much I think.
