### ISSUE TITLE
Category widget should be collapsible and be closed by default.

### ISSUE THREAD

**Issue by ssteinerx** [marvinlabs/customer-area#135]
Where there is a heirarchy of private files/pages categories e.g.:

```
Coverage
  2010
  2011
  2012

Monthly Reports
  2010
  2011
  2012
```
Coverage and Monthly Reports should be collapsed i.e. should work like Windows Explorer/Finder with a disclosure triangle next to the parent category.

**Comment by ssteinerx** [comment]
I implemented the "count of matching pages" but I'm not sure whether it's scoped to only items available to the current user since I don't have a good test data set up.

I also added the ability to set whether the count shows up in the widget interface settings.

If you could test the scoping to the current user (or add it if I didn't do it the customer-area way), I think this is a good addition to the widget.

**Comment by vpratfr** [comment]
Done
