### ISSUE TITLE
Better skins (admin/frontend)

### ISSUE THREAD

**Issue by vpratfr** [marvinlabs/customer-area#14]
### Admin side

get rid of the ugly CSS only skin and make that a little bit more organized and flexible.

- Use Less for the admin skin
- Use new logo
- better colors
- etc.

### Frontend side

- templates should not depend on bootstrap classes. Make CUAR specific classes (e.g. the container class is a compatibility problem with lots of 3rd-party themes)

**Comment by tlartaud** [comment]
Closing. Outdated issue.
