### ISSUE TITLE
Category hierarchies do not match between private file editor and category editor

### ISSUE THREAD

**Issue by ssteinerx** [marvinlabs/customer-area#153]
These two screnshots show the backend "Category Editor" and a file actually being edited.

In the Category editor (and in the database), the hierarchy shows correctly.

In the file editor, it shows that the item is assigned to a non-existent category and the hierarchy does not match that shown in the back end Category Editor.

This renders hierarchical categorization completely useless.

https://www.dropbox.com/s/1njm8859qfi3u3n/Screenshot%202015-08-16%2017.37.41.png?dl=0
https://www.dropbox.com/s/dvs2224s2zkjxrg/Screenshot%202015-08-16%2017.38.01.png?dl=0

**Comment by vpratfr** [comment]
The screenshot links point to 404 error. Please note that you can directly copy/paste screenshots within the github issue.

Please also check that the problem does not exist in the standard WP posts as well because we mainly rely on core functionnality to show the category checkboxes.

**Comment by vpratfr** [comment]
Any news about this one?

**Comment by ssteinerx** [comment]
Let me go look.  I now have my site running and 6.2.2 is behaving well so far.

**Comment by vpratfr** [comment]
ok thanks. I did not see any issue here when trying to reproduce.
