### ISSUE TITLE
"Advanced Filter" file categories dropdown does not populate from available categories

### ISSUE THREAD

**Issue by ssteinerx** [marvinlabs/customer-area#155]
Only choice is "Any"

**Comment by ssteinerx** [comment]
I completely reset customer-area (there should be an easy way to do this, btw) and now see the categories in the dropdown.

However...they do not properly reflect the hierarchy:
https://www.dropbox.com/s/473d1wl666m6t1d/Screenshot%202015-08-17%2007.41.45.png?dl=0
https://www.dropbox.com/s/7tn3ubdslhws4kc/Screenshot%202015-08-17%2007.42.08.png?dl=0

**Comment by vpratfr** [comment]
Fixed for 6.2
