### ISSUE TITLE
All files being shown to any logged in user

### ISSUE THREAD

**Issue by ssteinerx** [marvinlabs/customer-area#156]
Any logged in user, even a subscriber that is in no groups, can see any file in any category.

Like, completely doesn't do what it's supposed to.

**Comment by ssteinerx** [comment]
I am using the `develop` branch as it fixes some issues I was having before.  Is it possible that an update to the Managed Groups plugin could be necessary?

**Comment by ssteinerx** [comment]
Is there a way to reset the database so I can make sure there's not some sort of mangulation causing this symptom.

**Comment by ssteinerx** [comment]
I reset the database by deactivating the plugin and removing everything labeled cuar_*.  That seemed to leave everything in a clean state.  Re-enabled the plugin, made one file, for one user, and created a new user.  New user could see the file.  This just doesn't work at all any more.

**Comment by tlartaud** [comment]
Hi @ssteinerx,

The develop branch of the Managed Groups plugin does not have pending changes to fix this yet.

I don't know a way to reset the DB. The better solution would be to make fresh local installation to test that.

I will try to reproduce the bug right now and let you know.

**Comment by ssteinerx** [comment]
It's been a(nother) week.  Were you able to reproduce and when will there be a fix?

**Comment by vpratfr** [comment]
I think that this is indeed a compatibility error between the main plugin develop branch you are using and the add-on version which is older.

I have tried on the develop branch without any add-on and here is what I did:

- install WP
- activate main plugin, follow the wizard to create pages, set permissions
- create a subscriber user "subscriber1"
- create new file by admin user for the subscriber1 user
- create a subscriber user "subscriber2"
- log out
- log in as subscriber2
- getting the "you are not authorized to view this content" message as expected

You should not use the develop version of the plugin if you don't have the develop version of the add-ons. Please use the latest stable release for everything as we keep working on the develop branch and that of course sometimes needs updates to the add-ons.

**Comment by ssteinerx** [comment]
I am now using the released 6.2.2 and am experiencing the exact same symptom with Managed Groups Version 3.1.0:

Fresh install.

Create one managed group.

Add one Subscriber user to the group.

Upload one file for that managed group.

Login as ANY Subscriber, file shows up in dashboard.

Conclusion: Managed Groups does not work at all.
