### ISSUE TITLE
Duplicate Notifications

### ISSUE THREAD

**Issue by wpnicknz** [marvinlabs/customer-area#165]
1) If you are the author of a conversation, and a member of the project to which the conversation is owned by, you will get two emails. 
Adding $recipient_ids = array_unique($recipient_ids); to line 456 of notifications-addon.class.php resolves this

2) Functions "on_private_post_published" and "on_conversation_started" need a catch to stop an email being sent to author, similar to "on_new_reply_to_conversation" below;
if ( $user_id==$reply_author_id ) continue;

3) New conversation reply fires "on_private_post_published" and "on_new_reply_to_conversation" functions. Without the catch in point 2), the sender will get two emails as well.

**Comment by vpratfr** [comment]
Note to self : http://wp-customerarea.com/support/topic/notification-logic/#post-18257

**Comment by vpratfr** [comment]
Done, will be available in 7.0 & co.
