### ISSUE TITLE
WARN package.json customer-area@6.2.2 license should be a valid SPDX license expression

### ISSUE THREAD

**Issue by ssteinerx** [marvinlabs/customer-area#167]
I'm working on making a composer.json so I can install customer-area with Composer https://getcomposer.org/.

I figured I'd start with the package.json that's already there.

Tried 

```
npm install
```

And got this:
```
npm WARN package.json customer-area@6.2.2 license should be a valid SPDX license expression
```

Could you please add a composer.json file to the package?

Thanks,

S

**Comment by tlartaud** [comment]
Hi,

What are you talking about ?
Npm install and package.json has nothing to do with Composer.

Are you trying to install node dependencies, or are your trying to install php dependencies from composer ?
It's absolutely not the same.

But yes, we could add one.

**Comment by ssteinerx** [comment]
I'm well aware that they're not related, I was just seeing what package.json did and just reported the warning.

Yes, I'm suggesting that you add a composer.json.

**Comment by tlartaud** [comment]
@ssteinerx y, thx for the suggestion & report, will do that next week.

**Comment by ssteinerx** [comment]
And, possibly, something really cool like this beauty from Delicious Brains:

"url": "https://deliciousbrains.com/dl/wp-migrate-db-pro-latest.zip?license_key=<YOUR LICENSE KEY>&site_url=composer-test.dev"

So we can pull the latest straight from the source.  I'm setting up my own Composer repository for now, but it sure would be nice to have Composer support baked right in.

**Comment by vpratfr** [comment]
Hi,

I am seeing that warning too, but very franckly with all we have to do, that is a very minor thing which does not break anything. We'll fix it some day though. 

Composer.json may happen for the main plugin, but we currently have no plan to make anything for the addons. Not that we don't want to, because this is a nice and useful idea, but simply because we have lots to do on the plugin itself first (as you can see, we already have around 80 issues logged here).

**Comment by vpratfr** [comment]
Oh. By the way, you can install composer dependencies directly from a github repository even if it does not have a composer.json file or published on packagist.org (quick search will show you how if you don't already know that).

**Comment by ssteinerx** [comment]
Yes, I've got everything set up and made a quick python script to generate and add composer.json into the zips I downloaded from my account page.  That way I can keep multiple versions and control the upgrade process site-by-site with Composer.

**Comment by tlartaud** [comment]
@ssteinerx I don't understand what you are trying to do sorry.

Why don't you use wpackagist to install wp-plugins via composer ?

**Comment by ssteinerx** [comment]
It's not the main plugin; I can't install my wp-customerarea addons after downloading the zip files 'cause they don't contain a composer.json file.  I either have to generate one and add it to the zip file, or make a git repository out of the file I download, and update my git repository.  Simply adding an auto-generated composer.json file to your build process would make this all very convenient.

**Comment by ssteinerx** [comment]
Also, deliciousbrains has made this:

"url": "https://deliciousbrains.com/dl/wp-migrate-db-pro-latest.zip?license_key=&site_url=composer-test.dev"

Really, really handy...

S

**Comment by tlartaud** [comment]
@ssteinerx Really bad practice. You are going to add your licence key inside your composer.json in your repository.

You should create a private repository containing your addon (don't publish our add-ons publicly !!), and add via composer using git, and your SSH key.

**Comment by ssteinerx** [comment]
> @ssteinerx Really bad practice. You are going to add your licence key inside your composer.json in your repository.

No, I'm not;  I'm only going to publish private information to their private repository, that's the whole point.

> You should create a private repository containing your addon (don't publish our add-ons publicly !!),
See above.

> and add via composer using git, and your SSH key.
See above.

S

**Comment by vpratfr** [comment]
NPM warning should be fixed with that commit.

**Comment by ssteinerx** [comment]
I'm curious, why do you have a package.json file?

**Comment by vpratfr** [comment]
For our build system, currently nothing more. See also #179
