### ISSUE TITLE
Notification Recipient Enhancement

### ISSUE THREAD

**Issue by wpnicknz** [marvinlabs/customer-area#168]
It would be great if you could choose which user level received each email notification, in a format like the capabilities page.

**Comment by vpratfr** [comment]
Note to self : http://wp-customerarea.com/support/topic/notification-logic/#post-18257

**Comment by vpratfr** [comment]
Done, will be available in 7.0 & co. 

Implement filter `cuar/notifications/content` and make it return `false`.
