### ISSUE TITLE
If wp-content is moved, or wordpress is installed in a subdirectory, customer-area can't find its files

### ISSUE THREAD

**Issue by ssteinerx** [marvinlabs/customer-area#169]
I have this directory structure:
```
/
 /wp
 /wp-content
composer.json
.htaccess
index.php
wp-config.php
```
Wordpress is installed in wp, using the procedure documented in WordPress codex.

wp-config.php has been moved up into the root (above the wp directory) as has been possible since Version 2.6.

This is added to wp-config.php to relocate the wp-content directory:
```
define( 'WP_CONTENT_DIR', dirname(__FILE__) . '/wp-content' );
```

When navigating to the customer-area config in the admin, I get this in the console:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
http://host-7/wp/wp-content/plugins/customer-area/skins/admin/default-wp38/assets/img/logo-badge.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://host-7/wp/wp-content/plugins/customer-area/skins/admin/default-wp38/assets/css/styles.min.css?ver=4.3.1 Failed to load resource: the server responded with a status of 404 (Not Found)
```
Since I used WordPress codex documented methods for rearranging things, I'm not sure why this isn't working as expected.

There are so many  ways of doing this type of thing in WordPress that I'm not sure whether WordPress just isn't following along, or customer-area is using one of the calls that doesn't work in this particular situation.

**Comment by vpratfr** [comment]
There are other constants you should define too if you do that. Something like WP_CONTENT_URL I think

**Comment by ssteinerx** [comment]
Unfortunately, because of WordPress' "organic" (read disorganized) development, it's really hard to figure out what, exactly needs to be changed and the codex doesn't mention any of them.

For now, I've gone back to the awful way WordPress does it by default until I have time to delve further (God help me!).

S

**Comment by vpratfr** [comment]
Closing this because I have sites running perfectly the plugin and add-ons with the wp-content located somewhere else (e.g. the demos site)

**Comment by ssteinerx** [comment]
I'm sure it's related to my WP configuration but I followed the Codex.  Perhaps you could share the relevant portions of your config that make this error go away?  I know you mentioned WP_CONTENT_URL, but perhaps there's more?
