### ISSUE TITLE
Customer Area is incorrectly reporting that some addons need a newer version, there is no newer version

### ISSUE THREAD

**Issue by ssteinerx** [marvinlabs/customer-area#174]
https://www.dropbox.com/s/zmfpw950mr4b16g/Screenshot%202015-10-22%2018.09.44.png?dl=0

https://www.dropbox.com/s/skryupirwb23ex8/Screenshot%202015-10-22%2018.10.06.png?dl=0

**Comment by vpratfr** [comment]
You probably did not follow the update procedure (deactivate plugins before updating, then re-activate)

**Comment by ssteinerx** [comment]
I think I activated them in a batch without activating the main plugin first.  I still don't understand (and it doesn't say which one) why one thinks it needs a newer version.  Adding the "which plugin" info to the error message would be helpful.

**Comment by ssteinerx** [comment]
And, after deactivating them all, then reactivating in the correct order, customer-area still reports that it's running 6.1.x (even though 6.2.x is clearly installed).

**Comment by vpratfr** [comment]
This should be fixed with the new system to detect recommended addon versions
