### ISSUE TITLE
Missing function that main plugin is expecting to use; this was working in 6.0.x dev about a month ago

### ISSUE THREAD

**Issue by ssteinerx** [marvinlabs/customer-area#177]
Fatal error: Call to undefined method CUAR_PrivateFileAddOn::handle_copy_private_file_from_local_folder() in /home/xxxx/public_html/newsite/wp-content/plugins/customer-area/src/php/functions/functions-private-files.php on line 406

**Comment by vpratfr** [comment]
I fixed that yesterday. You can pull the corresponding function file from the develop branch.

**Comment by ssteinerx** [comment]
Thanks.  I hate to get off release versions because of my experience trying to get the sync working, but I guess I'll have to just pull this one file.

**Comment by ssteinerx** [comment]
The error is gone, but the file is not being copied.

**Comment by vpratfr** [comment]
If you look at the function comment, there is one big change: files have to be located in the ftp folder and you pass the file name (not the path) in the function parameters.

Also note that now you can attach more than just one file, I have removed the restriction about 1 file per post.

**Comment by ssteinerx** [comment]
Restricting it to the FTP folder is a giant step backwards, in my opinion.  My clients have several potential sync sources (Amazon S3, Dropbox, etc.) and having to copy them all to another folder on the machine creates a lot of extra work for no benefit other than slight simplification of the plugin code (because it's not as flexible).

**Comment by vpratfr** [comment]
Yes, this was a way to quick fix that. I will make it properly so that you can pass full-paths again.

**Comment by vpratfr** [comment]
Ok. This is now implemented. I needed to touch a few more file than just the functions file. You'll find all details in commit 7f8549f 

Here is some sample code to show you how to add a private file with 2 attachments:

```
        $res = cuar_create_private_file(
            array(
                'post_author' => 2,
                'post_title'  => 'This is my created file',
                'post_status' => 'publish'
            ),
            array(
                'type' => 'usr',
                'ids'  => array('1')
            ),
            array(
                array(
                    'name'   => '015.jpg',
                    'path'   => '/srv/my-path/',
                    'method' => 'noop'
                ),
                array(
                    'name'   => '016.jpg',
                    'path'   => '/srv/my-path/',
                    'method' => 'copy'
                )
            )
        );
```

`method` can either be:

- `copy` - copy the file from its source folder to the post's protected folder
- `move` - move the file from its source folder to the post's protected folder
- `noop` - keep the file in its source folder and serve downloads from there

**Comment by ssteinerx** [comment]
I *love* the noop option!  I've been symlinking in from a folder containing all of my various sync files but this will simplify my code enormously.  Thank you!  Since mycode is currently working, I won't be able to use this until I'm doing the next release of the project but I will then.  One thing I've been wondering about...do you have a set of (unpublished) unit tests for the main plugin?  I mostly work outside of the WordPress universe and wouldn't dream of trying to release a product without tests covering new features.  This could also speed the release cycle without having to worry about things like un-renamed functions slipping through the cracks (at least, not more than once).

**Comment by vpratfr** [comment]
Hi,

currently no unit testing is done. Unfortunatly. Mostly because when I started the plugin this was something I did not know. And also because testing in WordPress requires quite some work. 

I agree 100% though on the usefulness of them.
