### ISSUE TITLE
Replace package.json by a composer.json file?

### ISSUE THREAD

**Issue by vpratfr** [marvinlabs/customer-area#179]
From #167, we currently use package.json as a central place to store information about the plugin to be used by the build environment (version, text domain, etc.)

As NPM is not used at the plugin level, it may make sense to have a composer.json instead so that we can use some composer goodness in the future (autoloading, dependency management, etc.)

**Comment by vpratfr** [comment]
cc @ssteinerx

**Comment by ssteinerx** [comment]
Sounds like a wonderful idea!

**Comment by vpratfr** [comment]
Done
