### ISSUE TITLE
Specify the walker class to use for menu

### ISSUE THREAD

**Issue by tlartaud** [marvinlabs/customer-area#189]
To avoid conflicts with themes that modify the standard Walker Class used by WordPress for generating menus, we should specify our own by using `$walker` in `wp_nav_menu` call.

```
$walker
(object) (optional) Custom walker object to use (Note: You must pass an actual object to use, not a string)
Default: new Walker_Nav_Menu
```

**Comment by vpratfr** [comment]
Isn't that already available in the form of a filter?

```php
            $nav_menu_args = apply_filters('cuar/core/page/nav-menu-args', array(
                'theme_location'  => 'cuar_main_menu',
                'container_class' => 'menu-container cuar-menu-container',
                'menu_class'      => 'menu cuar-menu'
            ));
```

See: 

- In the [customer pages add-on](https://github.com/marvinlabs/customer-area/blob/dfaa3b66176b744cced32f48613e5723075072be/src/php/core-addons/customer-pages/customer-pages-addon.class.php#L836-L840)
- And in the [skin](https://github.com/marvinlabs/customer-area/blob/dfaa3b66176b744cced32f48613e5723075072be/skins/frontend/default-v4/cuar-functions.php#L23-L36)

**Comment by vpratfr** [comment]
Seems that the existing stuff covers the requirement. No need to add anything then. Thanks.
