### ISSUE TITLE
Navigation menu message appears even when menu is created

### ISSUE THREAD

**Issue by richems** [marvinlabs/customer-area#199]
I'm using the current up-to-date version of WP Customer Area, and keep getting the message below.

WP Customer Area has detected some potential issues:
1.The navigation menu for the customer area has not been created.

Even though I've clicked the button to fix the issue, and also deactivated and re-activated the plugin, there's no difference - it still appears.

Can anyone help on how to remove it?

Thanks

![image](https://cloud.githubusercontent.com/assets/16719628/12353539/dc484782-bb87-11e5-9cfe-e83f2fb70d36.png)

**Comment by vpratfr** [comment]
Deactivate then reactivate the plugin. Please read the update procedure as described in the documentation from the website
