### ISSUE TITLE
Global post data is not restored after secondary queries in print_associated_content

### ISSUE THREAD

**Issue by lop-cz** [marvinlabs/customer-area#205]
After the secondary queries in the **print_associated_content()** method of _CUAR_AbstractContainerPageAddOn_ class, the main query and global post data are not restored and stays on the last queried object (Private File or Page in case of the Project addon).

There should be a call to **wp_reset_query()** after inclusion of looping template on line 635.

**Comment by vpratfr** [comment]
Fixed. Will be available in next release.

If you find bugs and make fixes, feel free to make pull requests against our develop branch.

Thanks a lot for the reports!
