### ISSUE TITLE
Translations of Projects addon should be loaded earlier

### ISSUE THREAD

**Issue by lop-cz** [marvinlabs/customer-area#206]
Currently translations of the Projects addon (and probably other premium addons) are loaded by _init_ action a little bit later than _ProjectHelper_ is registering post type and this causes not translating all the labels of its custom post type and taxonomy.

The call for **load_textdomain** on line 68 of _CUAR_ProjectsAddOn_ should be done by **init** or **plugins_loaded** with lower priority. For example:

`add_action('plugins_loaded', array(&$this, 'load_textdomain'), 4);`

**Comment by vpratfr** [comment]
Done for every addon, will be available in next release.
