### ISSUE TITLE
Templates rewriting

### ISSUE THREAD

**Issue by tlartaud** [marvinlabs/customer-area#214]
- **(done)** All CPTs addons should use the collection template
- Shortcodes templates
- Widgets templates
- **(done)** Front-end publishing templates `customer-area/tasks/create-task-list/` and `customer-area/files/create-file/` : add the wizard less styles.
- Front-end publishing templates: polish the owner assignment fields
- Search template : add a 2cnd submit button to the main form. Maybe it could look like this
```
<input type="text" action="my2cndFormID">
<button type="submit" action="my2cndFormID">

// and the second form
<form id="my2cndFormID">
<input type="text">
// Others fields and filters here
<button type="submit">
</form>
```

**Comment by vpratfr** [comment]
Mostly done, rest is handled via Trello
