### ISSUE TITLE
master-skin tweaks

### ISSUE THREAD

**Issue by vpratfr** [marvinlabs/customer-area#222]
## Important
- [x] Wizard tabs : better responsive mode
- [x] Badge hover link on dark skin
- [x] Prefix .clearfix class to .cuar-clearfix to avoid conflicts
- [ ] ~~Reset navbar list LI to list-style:none~~
- [ ] ~~remove animated.less ?~~
- [ ] ~~optimally : any hex value should be removed from the less style files and converted into a variable from theme_variables.less~~
- [ ] ~~style ::selection **-> tried without success**~~
## Terminé
- [x] Tasklist edit tasks : pendant un save de la task, ajouter une classes qui calle une div transparent en position absolute par dessus, et plus rien ne peux se passer niveau clic, et niveau visu, rien ne se voit.
- [x] collection template : some tooltips should placed on the right, but make sure that on mobile size, they are switched back to the top or bottom position.
- [x] Nouvelle icone de loading à vérifier pour les différents CPTs
- [x] hover sur les collections doit être déclenché quand le curseur est sur l'item, pas seulement sur le thumb. Peut-être aussi changer légèrement la couleur de fond de l'item avec le hover du coup. **-> can't**
- [x] fancytree, slick and oll others Bower libs should be defined as fixed versions only
- [x] collections thumbnails should be at least proportionnals (min-height)
- [x] Add properties to the resets : float (.row), clear, visibility, content and mb some others ...
- [x] Show determinate progress on file uploads (instead of indeterminate) **What ??**
- [x] Sur une install fraiche, des sidebars vides sont crées pour certains types de contenus. Rajouter un test sur la sidebar pour savoir si elle est vide, et donc dans ce cas, ne pas l'afficher ?
- [x] tasklist : barre de progress plus épaisse (css) + pourcentage affiché à l'intérieur comme sur dashboard ?
- [x] les tooltips left n'ont pas de flêche (cf collection projets, tooltip de la team projet)
- [x] Couleur de texte sur un hover d'un statut pour le widget statut projet / facture **What ??**
- [x] http://wp-customerarea.com/support/topic/acces-a-un-fichier **Can't reproduce bug**
- [x] http://wp-customerarea.com/support/topic/probleme-daffichage-de-la-grille-sur-la-page-mes-fichiers-sur-safari/ **Can't reproduce bug**
- [x] Collections : si un propriétaire est sur 2 lignes ou +, aligner le texte en retrait par rapport à l'icone (sur le début du texte de la 1ere ligne)
- [x] add new master-colors skins
- [x] Archive pages should show a title before the collecion
- [x] Summernote popovers visibles initialement et non stylises correctement (cf creation contenu frontend)
- [x] double sidebar-scroller-bar on firefox ?
- [x] Certains boutons a.btn ont le soulignement sur le hover. Il faudrait le virer
- [x] Barre de progression non visible sur le upload d'un fichier en frontend
- [x] arrow border and color on conversation bubbles
- [x] Collections thumb view : missing width: 32% for screens sizes larger than -lg (body >= 1689px)
- [x] Champ select owner non visible entièrement en front si bcp d'owners dans 'users' (pb d'overflow je pense)
- [x] Reset the `text-align` and `border-width` properties on td and th (see dashboard on Sidney theme for example)
- [x] Create content add-on : _Warning: Missing argument 2 for CUAR_AbstractEditContentPageAddOn::print_submit_button() etc ....._
- [x] Problème sur le menu? cf [ce lien support](http://wp-customerarea.com/support/topic/drop-down-menu-doesnt-display-correctly/)
- [x] Remove wpca twenty-twelve+ and switch to a wpca-twenty-twelve-child with a custom functions.php file only. Cf comments below.
- [x] cuar-menu-container : buggy overflow on mobile size when the menu is outside cuar-content-container (see IMG_30052016_175306.png)

**Comment by tlartaud** [comment]
@vpratfr Issue à propos du select2 corrigé et fermée à l'instant : https://github.com/marvinlabs/customer-area/issues/223
J'imagine que celle que tu avais notée ici correspondait à la même chose :  _Champ select owner non visible entièrement en front si bcp d'owners dans 'users' (pb d'overflow je pense)_

Peux-tu stp faire un pull du build-env + wpca, et vérifier que c'est ok ? Les assets ont été ré-envoyés dans la foulée.

J'ai aussi passé nos libs bower en versions fixes, donc au apssage, fait un :
**grunt update-libs && grunt prepare-assets**

Si tu obtiens des fichiers (assets) compilés différents de ceux dans le dépôt, il y'a un soucis (=si tu peux les passer dans l'index sans qu'ils disparaissent : pas bon !!!)

**Comment by tlartaud** [comment]
@vpratfr Pour la barre d'upload, tu n'as pas traité le html de la même façon. Côté admin, tu utilise des div. Côté frontend, tu utilise des td, donc la barre d'upload doit être visible, mais fait environ 2 millimètres de large, et est donc placée sur la même ligne que le reste, tout à droite. Donc à mon avis, soit tu changes le tout en div comme le côté admin, soit tu met 2 TR par upload de fichier, et donc la barre dans le deuxième TR, et ça devrait fonctionner je pense ;)

**Comment by vpratfr** [comment]
@tlartaud 

Select2 : non pas corrigé.
---

![image](https://cloud.githubusercontent.com/assets/2526465/16238619/59bb2d76-37e1-11e6-9967-89989d3aec6a.png)

Sur ce screenshot, j'ai dans le dropdown normalement 5 utilisateurs sélectionnables. Le 5e est coupé par l'overflow en bas.

**Comment by tlartaud** [comment]
@vpratfr Euh, c'est moi ou le problème du select2 est de retour ? https://cl.ly/0t3i193P0S2V
