### ISSUE TITLE
Memory issues when viewing Private Files

### ISSUE THREAD

**Issue by phille97** [marvinlabs/customer-area#233]
Hello!

We have a wordpress site with over 4000 users and over 50 000 rows of usermeta.

A user reported that he/she couldn't see any private files, a quick look in the logs showed that some sql query in wordpress was causing the problem.

`2016/10/20 09:39:03 [error] 26476#26476: *11747 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes) in /var/www/customer_area_bug/wordpress/wp-includes/wp-db.php on line 2409" while reading upstream, client: 127.0.0.1, server: ---, request: "GET /wp-admin/admin.php?page=wpca-list%2Ccontent%2Ccuar_private_file HTTP/1.1"`

After some debugging I found this line

`$all_users = get_users(array('orderby' => 'display_name', 'fields' => 'all_with_meta'));`

at

[src/php/core-addons/admin-area/templates/private-post-list-filters-container.template.php#L6](https://github.com/marvinlabs/customer-area/blob/master/src/php/core-addons/admin-area/templates/private-post-list-filters-container.template.php#L6)
[src/php/core-addons/admin-area/templates/private-post-list-filters-content.template.php#L6](https://github.com/marvinlabs/customer-area/blob/master/src/php/core-addons/admin-area/templates/private-post-list-filters-content.template.php#L6)
[src/php/core-addons/post-owner/post-owner-user-owner-type.class.php#L104](https://github.com/marvinlabs/customer-area/blob/master/src/php/core-addons/post-owner/post-owner-user-owner-type.class.php#L104)

which I think produces a query similar to this

`SELECT user_id, meta_key, meta_value FROM wp_usermeta WHERE user_id IN (1,2,3,4,10,11, ... 4291,4292,4293,4294,4295) ORDER BY umeta_id ASC`

**Comment by tlartaud** [comment]
@phille97 Hi, you'r werlcome ! Thank you for your contribution.

**Comment by phille97** [comment]
![screenshot_2016-10-26_17-04-01](https://cloud.githubusercontent.com/assets/5407263/19731606/40118098-9b9e-11e6-8dc2-e0551b57cc19.png)

Using [select2 (ajax)](https://select2.github.io/options.html#ajax) I rebuilt the select so it's using a new ajax endpoint "cuar_get_users".

Some questions before I push the PR:

1. I made the file `src/js/admin/user-selector.js` How do I compile it into `assets/admin/js/customer-area.min.js`?
2. Is it ok if I remove `$all_users`? or will this break any compability?

**Comment by vpratfr** [comment]
It should be OK to remove all_users variable provided you migrate the filters that were used to build that list into your ajax end point.

Compiling the JS file can be done with our development environment. Look into our other repositories, you will see it easily. Named wpca-build-environment I think. 

If the file is required on frontend too (for owner selection that will be the case), place it in js/common instead of js/admin.

**Comment by RobertLidberg** [comment]
https://github.com/marvinlabs/customer-area/pull/234

**Comment by vpratfr** [comment]
Okay. We finally have a nice generic solution to this issue. Works everywhere (owner selection, advanced filters, switch users addon, etc.)

Thanks for the report and the PR which got us started.

Will be available in next release.

**Comment by rasmusjohansson** [comment]
Hi! The website Philip talked about has now grown to have more than 11 000 users and it is now having memory issues again. We know you fixed one of the files Philip reported but we noticed that the files

[src/php/core-addons/admin-area/templates/private-post-list-filters-container.template.php#L6](https://github.com/marvinlabs/customer-area/blob/master/src/php/core-addons/admin-area/templates/private-post-list-filters-container.template.php#L6)
[src/php/core-addons/admin-area/templates/private-post-list-filters-content.template.php#L6](
https://github.com/marvinlabs/customer-area/blob/master/src/php/core-addons/admin-area/templates/private-post-list-filters-content.template.php#L6)

still have the code that collects all users and their metadata:

`$all_users = get_users(array('orderby' => 'display_name', 'fields' => 'all_with_meta'));`

Would it be possible to change this to either only get the necessary meta fields or exclude users with the role subscriber?

**Comment by vpratfr** [comment]
Can be safely removed I think. Could you try and let us know?

Le mar. 14 août 2018 à 15:34, Rasmus Johansson <notifications@github.com> a
écrit :
