### ISSUE TITLE
Wrong collection layout width on large screens

### ISSUE THREAD

**Issue by vpratfr** [marvinlabs/customer-area#237]
From : https://wordpress.org/support/topic/files-and-pages-listed-in-one-column-if-theme-sidebar-is-disbaled/#post-8476416

> Hi!
> I’m using WP Customer Area with Generate Press free theme available at WordPress.org and I’ve found that if I use a page template without sidebars, Wp Customer Area Uses a two columns display for pages and files: one column for the files or pages (which are listed one per row), and another column for the WP Customer Area sidebar. This makes the interface centered in the middle with plenty of whitespace on both sides and makes it look very narrow.
> I’ve found it impossible to correct using CSS.

Screenshots attached on original support request

**Comment by tlartaud** [comment]
Fixed in 7.2
