### ISSUE TITLE
Use one single template file to override all templates

### ISSUE THREAD

**Issue by wpchannel** [marvinlabs/customer-area#238]
Sometimes it's not necessary to have 5 differents templates files for customizations in our theme:

- single-cuar_private_file.php for a private file
- single-cuar_private_page.php for a private page
- single-cuar_conversation.php for a conversation
- single-cuar_tasklist.php page for a list of tasks
- single-cuar_project.php page for a project

It would be great to use a unique PHP file like cuar.php to manage all of them. :)

**Comment by tlartaud** [comment]
Hi,

This is actually not doable, but you can for now simply create a seperate `templates/layout.php` and include it in each `single-cuar_*` file.

In the meantime, I do not really recommend to do that. Even if for now, layouts looks like pretty much the same, we have planned to adapt them in the future depending on the content which is displayed for each post type. For example, the conversations layout will be rebuilt when I'll have the time for this, to make it looks like something more closer to classic gmail or outlook interfaces.

I let @vpratfr decide weither if it should be added as a feature request or not.

Thank you for your feedback.

**Comment by wpchannel** [comment]
Thanks @tlartaud ! :)

**Comment by vpratfr** [comment]
Done. Will be in 7.2

**Comment by vpratfr** [comment]
#### For single private content (ex: private file "Test")

- single-cuar_private_file-test.php
- single-cuar_private_file.php
- cuar-single.php
- cuar.php
- single.php

#### For a WP Customer Area page (ex: dashboard, id=550)

- page-dashboard.php
- page-550.php
- cuar-page.php
- cuar.php
- page.php

**Comment by tlartaud** [comment]
@wpchannel I've also added a function named `cuar_the_single_content();` that you can use in `single-*.php` instead of `the_content();` to import the whole private area including menus, headers, footers, and so on, so you make you won't miss any content.

If you need a fully customized area instead, you can use standalone functions, such as `customer_area_menu()` and so on ...
