### ISSUE TITLE
Use 'Enter' to add tasks

### ISSUE THREAD

**Issue by jevin** [marvinlabs/customer-area#240]
Right now, the "Add task" button has to be clicked to add tasks. Hitting "Enter" key does nothing. Not sure if that's intended behavior or something went wrong?

It would be great if we could hit "Enter" to add new tasks.

**Comment by vpratfr** [comment]
Hi,

hitting `tab` and then `enter` will do what you want.

We did not want enter to send the text to avoid mistakes and to allow maybe in the future to have multiple paragraphs within the task details.
