### ISSUE TITLE
Unused sidebar removal filter

### ISSUE THREAD

**Issue by tlartaud** [marvinlabs/customer-area#244]
See https://wp-customerarea.com/support/topic/code-snipper-for-sidebar-removal-does-not-work/#post-66668

The filter to remove the unused sidebar is not working because not used.

The cause is here
See https://github.com/marvinlabs/customer-area/blob/master/src/php/core-classes/addon-page.class.php#L420

Solution : before creating each default widget, check the filter to see is `has_default_sidebar` is still true, OR simply remove this filter because we also have `cuar/core/page/enable-sidebar?slug` filter.

Doc should be updated : https://wp-customerarea.com/snippet/disable-default-sidebar/

**Comment by tlartaud** [comment]
Edit

It looks like that $page_slug is wrong. Not matter on which page we are, it always return customer-dashboard slug.

si je comment out la ligne 58 dans public/app/plugins/customer-area/src/php/core-addons/customer-dashboard/customer-dashboard-addon.class.php ca me retourne le bon slug déjà, mais le filtre marche toujours pas

`
public function run_addon( $plugin ) {
  parent::run_addon( $plugin );  
  
  // Widget area for our sidebar
  //$this->enable_sidebar();
 }`

The second problem is that `$this->enable_sidebar` is called inside functions `run_addon` which is run before theme initialisation, and before theme functions.php is getting loaded, so, the filter is not applied.

The enable sidebar function should be moved into a function initialized via a filter (eg. 'after_theme_setup`, ìnit` and so on ..)

**Comment by vpratfr** [comment]
Works as intented as long as the filter/hook is placed inside a plugin and not inside the theme.
