### ISSUE TITLE
Allow some notification types to be sent to the current user

### ISSUE THREAD

**Issue by vpratfr** [marvinlabs/customer-area#265]
// Unless this is a test, assume that the currently logged user does not need to get notified of his own actions
        if ($notification_id!='test' && $recipient_id==get_current_user_id()) return;

customer-area-notifications/src/php/helpers/notifications-mailer-helper.class.php
ligne 75

Payments for instance should be sent to the current user.

**Comment by vpratfr** [comment]
We should have a white list of notifications which can be sent to current user.

**Comment by tlartaud** [comment]
@vpratfr I think we should also improve the notifications UI. Maybe we could add a form, for instance in the invoice edit screen -> notification panel, which could help the author of the post to select exactly the users that can be notified. For instance, once the invoice is published, it can be useful that the author of the post is absolutely sure that the users that need to be notified will be notified, like:
- the author of the invoice post
- the user assigned to the invoice
- another user which is in the same group as the user assigned to the invoice
- another manually selected administrator
- another manually entered emails using select2 multiple field

Plus, a great improvement would be to display a table listing all notifications that get sent, when, to whom, etc.

**Comment by vpratfr** [comment]
Moved improvements to own issue (#268).

Rest is fixed.
