### ISSUE TITLE
Bug: invoice notification not sent to the client

### ISSUE THREAD

**Issue by vpratfr** [marvinlabs/customer-area#269]
Pourquoi deux notifications ont été envoyées à Thomas Lartaud, l'auteur du post, et vpratfr_be76e5hl ? C'est carrément bizarre en fait ....

Quand je lis la checkbox, j'ai plutôt l'impression que ça va envoyer la facture au client que j'ai sélectionné, ou même tous les owners, par exemple :

l'auteur du post invoice
l'utilisateur assigné
éventuellement les autres groupes d'utilisateurs assignés
Mais que vient faire vpratfr_be76e5hl dans l'affaire, et ou est passé le mail de notifs aux personnes assignées ?

See: https://trello.com/c/Z8vdVLdO

**Comment by tlartaud** [comment]
Fixed.
