### ISSUE TITLE
select2 issue with protect post field

### ISSUE THREAD

**Issue by tlartaud** [marvinlabs/customer-area#280]
![image](https://user-images.githubusercontent.com/494234/33179955-6cb42d0a-d06b-11e7-92b4-61c017fedf39.png)

**Comment by tlartaud** [comment]
Other issue
![image](https://user-images.githubusercontent.com/494234/33181079-387e4440-d06f-11e7-8d5e-c0a3593d8668.png)

By reading this piece of code, it looks like checking the box should hide the fields, but its not hidding it.

**Comment by vpratfr** [comment]
Yep. To fix.

**Comment by tlartaud** [comment]
Done
