### ISSUE TITLE
Project notification

### ISSUE THREAD

**Issue by sbodewes** [marvinlabs/customer-area#284]
Dear,

We are using projects in combination with notifications, but when i use the option notify users they can access the project, the complete website crashes and i receive the email notification over 200 times :|

i hope to hear from you soon!

Sander Bodewes

**Comment by vpratfr** [comment]
Hi

Can you open a support request on our forum? Please provide some more info:
in the plugin logs, do you see messages as duplicates?

Also, can you try to reproduce this with a small set of owners? Like 2
owners, do you get 2 emails?

Regards

**Comment by tlartaud** [comment]
@sbodewes Hi, this issue has been recently solved. You can update the notifications and project addons from your download page.

Best regards.
