### ISSUE TITLE
Page break, New Pages, Pagination - on private pages don't work !

### ISSUE THREAD

**Issue by bankir9** [marvinlabs/customer-area#306]
![0077](https://user-images.githubusercontent.com/40299572/41474543-ed9b3446-70c4-11e8-82b6-5c8b2bbfa458.jpg)

**Comment by tlartaud** [comment]
Hi,

Could you explain please ?

What you are showing on this screenshot is not from WP Customer Area. It probably comes from your theme.

See our documentation about themes development. You can create a `cuar.php` template from `page.php` and edit it to remove unused or buggy stuffs from your theme templates.

Regards.

**Comment by vpratfr** [comment]
Additionally, please use the support forum on the plugin website to request support. We use this issue board to monitor verified bugs and feature requests. Thanks.
