### ISSUE TITLE
Re-organise main menu & pages

### ISSUE THREAD

**Issue by vpratfr** [marvinlabs/customer-area#31]
In the admin, try to reorganise pages, less submenu items (ex: file categories could be accessible from the files list page maybe)

**Comment by vpratfr** [comment]
Making good progress as of 97a12a7cd519b2840f24d15423f39e9b01c2b88e 

Currently, we have gained:

- a leaner menu 
- settings got moved to the WordPress settings menu
- new list tables for all private content types (files, projects, task lists, ...) with advanced filters

What is missing:

- the adminbar menu has been removed for compatibility reasons currently, would be good to restore it and use the improvements we gave to the main menu
- Better list table & filters for the owner list pages (user groups in add-ons)

**Comment by vpratfr** [comment]
@tlartaud @ssteinerx Would love some feedback on this one. (for thomas, addons have some branches with the same name "feature/admin-cleanup")

**Comment by ssteinerx** [comment]
I'm getting "An error happened while uploading your file: Specified file failed upload test." with .png, .pdf, and .txt.  I'm doing this on my local machine under MAMP.  Only plugin active is Customer Area, up to date with feature/insert-functions.

**Comment by ssteinerx** [comment]
Getting odd: "Specified file failed upload test" from file.php but file is in correct place in Customer Area hierarchy.  Any clue?

**Comment by vpratfr** [comment]
Does that have to do with this feature or is that about the insert function?

**Comment by ssteinerx** [comment]
I don't know what is causing it, I've never seen it before.  I've got the insert feature branch checked out and up to date.

The strange thing is that the file ends up where it's supposed to.

S

**Comment by vpratfr** [comment]
Let's consider we have something good enough for now. On to beta testing.

@ssteinerx I have merged those changes in your branch "feature/insert-functions". Let me know how it looks like.

**Comment by ssteinerx** [comment]
I have the managed groups plugin installed but I can't figure out where I'm supposed to administer groups; it used to be in the sidebar menu.

**Comment by vpratfr** [comment]
I'll send you an updated version for the add-ons for compatibility with this beta version. Check your mails soon.

**Comment by vpratfr** [comment]
@ssteinerx You have an email with the addons

**Comment by ssteinerx** [comment]
Ok, great.  Unfortunately, the group functionality is the cornerstone of my sync code and I'm dead in the water without it.  The only one I need or have installed on my test system is managed groups.

Thanks,

S

**Comment by ssteinerx** [comment]
Great, thank you!  I'll let you know how it goes...

Steve

**Comment by ssteinerx** [comment]
The "Managed Groups" item has come back to the admin menu, but clicking it gives a 404 error.

Do I have to regenerate the templates or something?

S

**Comment by ssteinerx** [comment]
The "Managed Groups" link in the sidebar 404s, the links in the WP Customer Area at the top of the screen do work.

S

**Comment by vpratfr** [comment]
@ssteinerx  Ok. I have emailed the updates for 2 add-ons and also merged some fixes from develop in your branch.
