### ISSUE TITLE
page templates 

### ISSUE THREAD

**Issue by vpratfr** [marvinlabs/customer-area#52]
From: https://wordpress.org/support/topic/using-page-templates

In my theme I can use FULLWIDTH for pages, but I can't display that box in Private Pages. How can I add this, in order to use choose if I need to use full width rivate pages?

**Comment by danicasati** [comment]
Must-have feature!

**Comment by vpratfr** [comment]
This is a feature that depends on the theme. The plugin cannot guess if the theme implements that or not. Hence we cannot add this feature. 

We have lots of `theme_supports` hooks for theme developers which should make their life easy though.
