### ISSUE TITLE
Customer Area CSS conflict with template

### ISSUE THREAD

**Issue by demirn** [marvinlabs/customer-area#63]
Hello,

my website is ayonix dot com.
After i installed customer area the wpml language switcher is gone.

When i disable the option "Include the default stylesheet." Then it works good, but the nav menu in customer area seems then awful.

**Comment by vpratfr** [comment]
Hi,

this may be a conflict with WPML (by the way, Customer Area is not fully compatible with WPML, see #29). 
or this could be related to #9 too
or simply the default stylesheet has a conflicting rule with either the WPML stylesheet or your theme's stylesheet.

**Comment by demirn** [comment]
couldn't you tell me a solution? maybe a css customization will be enough for me. Couldn't you please help me? The others tell me that its because of customer area..

**Comment by vpratfr** [comment]
You can add all CSS customizations to your theme's stylesheet, no worries. However, I can't precisely tell you what is causing the problem. If you don't have the knowledge, please try to contact a web designer in your area to sort it out for you.

Regards,
