### ISSUE TITLE
New skin system

### ISSUE THREAD

**Issue by vpratfr** [marvinlabs/customer-area#68]
Because default-v4 has its own issues, the best would be to start a new skin for WP Customer Area that would be much more compatible with 3rd party themes.

- Make a `master` skin in `skins/frontend/master`
- That skin should only use `cuar-*` classes, we will get rid of all other class names (no template file in should contain a CSS class not prefixed by `cuar-`)
- The master skin should be based on LESS variables in its main file so that we can easily create child skins without copying the whole master skin

This should help with #15, #14, #11, #9

**Comment by dev169** [comment]
My vote for this, as i am running into it. There are often very subtle changes to the parent theme that are hard to track down. 

I think the best way to start would be by conditionally loading the CSS only when needed: in cuar-* custom post types and the client area. This would mitigate a lot of the issues for the time being, and buy some time until the skin is reworked.

**Comment by vpratfr** [comment]
@dev169 the skin is currently being reworked. should be in 6.2 I think, maybe even 6.1 if Thomas can do wonders. All CSS classes used by the plugin will be prefixed by ´cuar-´ eliminating all conflicts with any other CSS.

**Comment by vpratfr** [comment]
Sorry, another delay, Thomas is making this the proper way and hence it takes more time than planned. Target is 7.0

**Comment by tlartaud** [comment]
Closing. This issue is too generic. The new skin is actually rebuilt and need some more few tweaks.
