### ISSUE TITLE
Assign other post types to customer

### ISSUE THREAD

**Issue by dev169** [marvinlabs/customer-area#75]
I would be very useful to be able to include in the customer's dashboard custom post types created by other plugins, or even regular posts. For instance, I want to use a [PixProof](https://wordpress.org/plugins/pixproof/) gallery, and assign ownership to a customer, so that it will be listed under his "Private pages". 

Is this possible?

**Comment by vpratfr** [comment]
I don't know if it is possible currently, but it is certainly not trivial. I have been thinking about this possibility for quite some time so I guess I'll give it a try some day. Marking this for 6.3.

**Comment by vpratfr** [comment]
@dev169 Would you like to beta test our add-on ? This is currently being developed and we'd like your feedback on that.

**Comment by vpratfr** [comment]
Ok, marking this as closed. If anything, we'll open new issues.
