### ISSUE TITLE
Error on feature/insert-functions branch

### ISSUE THREAD

**Issue by ssteinerx** [marvinlabs/customer-area#78]
Fatal error: Class 'CUAR_CustomPost' not found in /XXXX/wp-content/plugins/customer-area/src/php/core-classes/Log/log-event.class.php on line 21

I'm attempting to install just the main Customer Area plugin and there seems to have been some fragmenting of the development branch.

If you could please resolve in the main repo (merge back to develop, then rebase?), I'll be delighted to keep working on the insert-functions branch...

Thanks,
Steve/ssteinerX

**Comment by vpratfr** [comment]
Should be fine now
