### ISSUE TITLE
Custom Translation files

### ISSUE THREAD

**Issue by vpratfr** [marvinlabs/customer-area#80]
When making custom changes/additions to a translation, it will be overridden on plugin update. So please integrate a check if there’s any translation files in a themes ‘languages’-folder and/or in ‘wp-content/languages/plugins’.

From: http://wp-customerarea.com/support/topic/custom-translations/

**Comment by lennynld** [comment]
Hello Vincent,

as we speak i'm translating some of the add-ons to dutch is it an idea to help you guys to translate the plug-in and add-ons to dutch? 
If you got any questions please let me know

Best regards 
Lennart

**Comment by vpratfr** [comment]
Hi, sure. That would be great. 

For the addons just send them to us by email (support@wp-customerarea.com)

For the main plugin, we have a transifex project online and you'll be able to translate everything easily there: https://www.transifex.com/projects/p/wp-customer-area/

**Comment by lennynld** [comment]
Hi vincent,
i just send you a wetransfer mail with the files.

**Comment by vpratfr** [comment]
@lennynld Fixed.

[Documentation updated](http://wp-customerarea.com/documentation/translating-wpca/)

> ### Where to store your translation files?

> In order not to loose the translations you have made after plugin updates, WP Customer Area allows to store the language files in various safe locations. You can put your PO and MO files in any of those locations:

> * wp-content/customer-area/languages
> * wp-content/languages/customer-area
> * wp-content/languages
