### ISSUE TITLE
feature/insert-functions: Uploaded file 'view post' display is a mess with default template & zoom

### ISSUE THREAD

**Issue by ssteinerx** [marvinlabs/customer-area#81]
https://www.dropbox.com/s/zgjrk4da9a7edly/Screenshot%202015-04-12%2010.24.08.png?dl=0

**Comment by vpratfr** [comment]
This is a theme problem, not plugin's fault. For information our official development theme is Twenty Twelve (or even better Twenty twelve+ which can be found on the plugin website and github too)
