### ISSUE TITLE
Clicking on link in "Object" column of log goes to list of objects instead of the listed one

### ISSUE THREAD

**Issue by ssteinerx** [marvinlabs/customer-area#84]
Shouldn't it link directly to the object's edit page?  Since the ID isn't shown in the Private Files page, the link is pretty useless since you can't tell which file "File 24" is when you get to the Private Files page.

Having the ID as a column in the Private Files page would be useful anyway, but the link should go to the right object.

**Comment by vpratfr** [comment]
Done
