### ISSUE TITLE
There seem to be two different "Private Files" templates, no visual clue other than missing buttons

### ISSUE THREAD

**Issue by ssteinerx** [marvinlabs/customer-area#85]
When you click on an object link in the Log, you get a Private Files list that, now that I am looking more closely, shows all the files for a particular user/group.

Unfortunately, it is not shown anywhere on the page that the list is filtered in any way.

When you just click on "Files" in the sidebar menu, you are brought to a similar looking page, but it shows owner info as well.

There should be an indication that the list of files is limited, and should show the limiting criteria i.e. "Files for Customer Name."

**Comment by vpratfr** [comment]
Fix to #84 should make this unnecessary.
