### ISSUE TITLE
Conversations

### ISSUE THREAD

**Issue by lennynld** [marvinlabs/customer-area#86]
I get this error when i enter the page to reply 
(http://www.loveyoudesign.com/klantenzone/conversations/my-conversations/2015/04/13/test/)

Parse error: syntax error, unexpected '->' (T_OBJECT_OPERATOR) in /home/loveyoudesign.com/public_html/wordpress/wp-content/plugins/customer-area-conversations/src/php/customer-conversations/templates/customer-conversations-single-post-reply-list.template.php on line 7

**Comment by vpratfr** [comment]
Hi,

Yes, this bug has been identified and will be fixed in the next release. 

You have a quick solution on [this topic of our forum](http://wp-customerarea.com/support/topic/conversations-parse-error/)

Regards,

**Comment by lennynld** [comment]
thanks
