### ISSUE TITLE
Lots of "owner changed" log entries where the owner didn't actually change

### ISSUE THREAD

**Issue by ssteinerx** [marvinlabs/customer-area#87]
Editing a post with an attached file seems to always produce an "Owner changed" event, even when  the owner doesn't actually change:

2015/04/13 - 1:17:10	Owner changed	File 80	IP admin	From: Managed Group - Group 1-2 To: Managed Group - Group 1-2

**Comment by vpratfr** [comment]
Fixed. Thanks, good catch.

@ssteinerx What do you think about the insert functions branch, is that good enough for your needs? If it is, then I will merge it into the develop branch.

**Comment by ssteinerx** [comment]
@vpratfr I'm writing the part that uses those new functions today; I'll let you know how it goes.  I wrote the other half in Python because PHP.
