### ISSUE TITLE
Navigation menu shows up on post widgets

### ISSUE THREAD

**Issue by vpratfr** [marvinlabs/customer-area#90]
The navigation menu is showing up in various places when other posts are shown (most probably because we don't check the post type of the post currently being displayed properly)

From: https://wordpress.org/support/topic/plugin-is-everywhere-visible

![image](https://cloud.githubusercontent.com/assets/2526465/7178300/09c71f12-e42e-11e4-964f-2483de90bd6b.png)

**Comment by tlartaud** [comment]
We should add a check inside our main function added as a filter to `the_content` with `is_main_query` to not let the menu appears everywhere a bad coded theme use `the_content`.

Also from : https://wp-customerarea.com/support/topic/duplicated-menu/

**Comment by vpratfr** [comment]
So far no bug reports from that date. So closing for now.
