### ISSUE TITLE
Getting error trying to call cuar_bulk_create_private_files()

### ISSUE THREAD

**Issue by ssteinerx** [marvinlabs/customer-area#91]
https://www.dropbox.com/s/mw13xo3p7pczr7c/Screenshot%202015-04-16%2014.47.59.png?dl=0

Not sure how to determine when it's safe to call, but the returned value of cuar_addon('post-owner') is null at the time I'm trying to call it (in the constructor of the admin area for my plugin).

Perhaps this is why you tend to use so  many filters?  To make sure everything's there before it gets called?

**Comment by vpratfr** [comment]
You can call this fonction only after the plugin is ready. So the "init" hook should be a good time to do it.
