### ISSUE TITLE
Manually add new .txt file to managed group by direct upload.  After upload redirects to 404, file not saved.

### ISSUE THREAD

**Issue by ssteinerx** [marvinlabs/customer-area#96]
The file shows up as a Draft in the files list, but the attachment is not saved.

This is in wp-admin/error_log:

[20-Apr-2015 17:33:58 UTC] PHP Notice:  Undefined variable: is_locked in /home/xxx/public_html/newsite/wp-content/plugins/customer-area/src/php/core-addons/admin-area/templates/private-post-list-filters-row-author.template.php on line 9

No other errors (other than the 404 on redirect) are shown or in error_log files.

Also, I just noticed that there are no subdirectories of wp-content/customer-area.  I had wiped them out after deleting a bunch of test files (through the WP admin area), but expected any that were needed would be recreated.

To test this further, I went to create a new Managed Group to see whether its file directory would be created and got this just after the admin header:

Notice: Undefined index: wp_cuar_nonce_members in /home/rushtong/public_html/newsite/wp-content/plugins/customer-area-managed-groups/src/php/managed-groups-admin-interface.class.php on line 319

I created a new managed group, but no directory was created within wp-content/customer-area.

I have removed all .htaccess files other than the default WordPress one in the root.

I still have the file redirection to 404 issue.

**Comment by ssteinerx** [comment]
Then I tried uploading a file to my new group and got: 

Notice: Undefined index: cuar_ftp_delete_file_after_copy in /home/xxx/public_html/newsite/wp-content/plugins/customer-area/src/php/core-addons/private-file/private-file-admin-interface.class.php on line 236

This appears to be due to a missing setting.  I had a previous version of customer-area on this site, but I don't think I deactivated it (so as to not lose my settings); just replaced with a Version 6.1 checkout from the features/insert-file branch.

**Comment by ssteinerx** [comment]
The problem seems to be that the directory is not recreated and the missing directory messes up the upload but the error is not handled well, and the post is left in an unpublished state leading to the 404.

If the directory is recreated, then a new private file uploaded, the upload redirects to regular "Posts" which also does not seem right.

**Comment by vpratfr** [comment]
@ssteinerx Do you still have this issue? Or has this been fixed by #94?

**Comment by ssteinerx** [comment]
I'll check it today.

**Comment by ssteinerx** [comment]
This issue occurs when the customer-area private folder for the owner is deleted behind the scenes.  While this should never occur in practice, the error handling is less than ideal...

I'd mark this as an enhancement in a separate bug.  Closing this one.
