### ISSUE TITLE
Allow subdirectories within Customer Areas

### ISSUE THREAD

**Issue by ssteinerx** [marvinlabs/customer-area#97]
Use case: Site owner provides monthly reports to customers.  Site owner wishes to mirror existing directory structure virtually identical to WordPress wp-content/uploads directory structure.

I'm not sure how common this organizational structure is, but my clients use it, I'd like to use it for their reports, and it seems like a good general improvement.

I'll be willing to help on this, but I still don't know the customer-area code well enough to even suggest how to implement it.

**Comment by ssteinerx** [comment]
The problem I'm running into right now is that I have this:

   Customer
      - 2000
        - Report.doc
     - 2001
        - Report.doc

When I sync, I get the source file name "s3source/Customer/2000/Report.doc" and want to find out if it's newer than the one in the customer-area for that Customer.  Unfortunately, duplicate file names are handled in customer-area by being made unique by adding a character that differentiates it from all the others with the same name.  So...I can't tell which one to compare my source document to as the path info has disappeared.

I am probably going to have to make them into 2000-Report.doc and 2001-Report.doc to get my client's project done, but that's not an ideal solution, obviously.

**Comment by vpratfr** [comment]
@ssteinerx Yes, I think flattening the file hierarchy is a good way to handle it. I don't think I want to get into a file hierarchy for the secured files as this would complicated things quite a bit. 

If you ever implement this as a pull request, please take care of making a lot of tests.

**Comment by vpratfr** [comment]
Marking as "won't fix", if you have a working, tested and backwards-compatible PR, I will consider merging it though.
